name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install Dependencies
      run: npm install

    - name: Build APK
      run: npx react-native run-android
